spring:
  application:
    name: meditrack-backend

  datasource:
    url: jdbc:postgresql://localhost:5432/meditrack
    username: postgres
    password: 1212120000

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    defer-datasource-initialization: true

  sql:
    init:
      mode: always
      data-locations: classpath:data.sql