spring:
  application:
    name: meditrack-backend

  datasource:
    url: jdbc:postgresql://localhost:5432/meditrack
    username: postgres
    password: Kharbita+2005

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
