spring:
  application:
    name: meditrack-backend

  datasource:
    url: jdbc:postgresql://localhost:5432/meditrack
    username: postgres
    password: 1742005

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

  sql:
    init:
      mode: always
      data-locations: classpath:data.sql